apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: secureops-management-data
  namespace: secureops
  labels:
    app: secureops
    plane: management
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi
