CREATE TYPE "public"."asset_status" AS ENUM('active', 'inactive', 'decommissioned', 'quarantined');--> statement-breakpoint
CREATE TABLE "assets" (
	"id" serial PRIMARY KEY NOT NULL,
	"tenant_id" integer NOT NULL,
	"hostname" varchar(255) NOT NULL,
	"ip_address" varchar(100),
	"ipv6_address" varchar(200),
	"mac_address" varchar(50),
	"endpoint_type" varchar(50),
	"operating_system" varchar(200),
	"agent_version" varchar(100),
	"content_version" varchar(100),
	"user_name" varchar(255),
	"endpoint_alias" varchar(255),
	"endpoint_group" varchar(255),
	"prevention_policy" varchar(255),
	"extensions_policy" varchar(255),
	"deployment_type" varchar(50),
	"cloud_provider" varchar(100),
	"cloud_region" varchar(100),
	"cloud_instance_id" varchar(200),
	"tags" text,
	"last_seen" timestamp,
	"last_upgrade_status" varchar(100),
	"last_upgrade_time" timestamp,
	"status" "asset_status" DEFAULT 'active' NOT NULL,
	"risk_level" varchar(20),
	"risk_score" integer,
	"incident_count" integer DEFAULT 0,
	"vulnerability_count" integer DEFAULT 0,
	"enrichment_data" jsonb,
	"source" varchar(100) DEFAULT 'import',
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_assets" (
	"id" serial PRIMARY KEY NOT NULL,
	"tenant_id" integer NOT NULL,
	"user_name" varchar(255) NOT NULL,
	"email" varchar(255),
	"department" varchar(255),
	"title" varchar(255),
	"total_requests" integer DEFAULT 0,
	"allowed_requests" integer DEFAULT 0,
	"denied_requests" integer DEFAULT 0,
	"isolated_requests" integer DEFAULT 0,
	"sites_visited" integer DEFAULT 0,
	"total_bytes_mb" integer DEFAULT 0,
	"downloaded_bytes_mb" integer DEFAULT 0,
	"uploaded_bytes_mb" integer DEFAULT 0,
	"risk_level" varchar(20),
	"risk_score" integer DEFAULT 0,
	"reputation" varchar(100),
	"top_sites" jsonb,
	"url_categories" varchar(1000),
	"application_names" varchar(1000),
	"linked_asset_ids" jsonb,
	"activity_data" jsonb,
	"source" varchar(100) DEFAULT 'import',
	"user_status" varchar(20) DEFAULT 'active',
	"last_activity" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "assets" ADD CONSTRAINT "assets_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_assets" ADD CONSTRAINT "user_assets_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;