apiVersion: v1
kind: Service
metadata:
  name: secureops-storage
  namespace: secureops
  labels:
    app: secureops
    component: storage
spec:
  type: ClusterIP
  selector:
    app: secureops
    component: storage
  ports:
    - name: http
      port: 5000
      targetPort: http
      protocol: TCP
