apiVersion: v1
kind: ConfigMap
metadata:
  name: secureops-data-plane-config
  namespace: secureops
  labels:
    app: secureops
    plane: data
data:
  region: "eu-west"
  opensearch-url: "https://opensearch.secureops.svc.cluster.local:9200"
  object-storage-bucket: "secureops-events-eu-west"
  object-storage-region: "eu-west-1"
  hot-retention-days: "90"
  warm-retention-days: "365"
  cold-retention-days: "1095"
  compression-after-days: "7"
  log-level: "info"
