apiVersion: v1
kind: Service
metadata:
  name: secureops-data-plane
  namespace: secureops
  labels:
    app: secureops
    plane: data
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: secureops
    plane: data
