{{- if and .Values.dataPlane.enabled .Values.dataPlane.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "secureops.fullname" . }}-data-plane-hot
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secureops.labels" . | nindent 4 }}
    plane: data
    tier: hot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.global.storageClass }}
  resources:
    requests:
      storage: {{ .Values.dataPlane.persistence.hotStorage.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "secureops.fullname" . }}-data-plane-cold
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secureops.labels" . | nindent 4 }}
    plane: data
    tier: cold
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.global.storageClass }}
  resources:
    requests:
      storage: {{ .Values.dataPlane.persistence.coldStorage.size }}
{{- end }}
