{{- if .Values.serviceAccount.create }}
{{- $fullname := include "secureops.fullname" . -}}
{{- $labels := include "secureops.labels" . -}}
{{- $services := list "management" "receiver" "collector" "normalizer" "detection-engine" "enrichment" "storage" "data-plane" -}}
{{- range $service := $services }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullname }}-{{ $service }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- $labels | nindent 4 }}
    app.kubernetes.io/component: {{ $service }}
    {{- with $.Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $.Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $.Values.serviceAccount.automountToken | default true }}
{{- end }}
{{- end }}
